version: '3'

services:
  postgres:
    image: postgres:15-alpine # AWS Aurora PostgreSQL compatible version
    environment:
      POSTGRES_DB: payload
      POSTGRES_USER: payload
      POSTGRES_PASSWORD: payload
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U payload']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - payload-network

volumes:
  postgres_data:
  node_modules:
  