version: '3'

services:
  postgres:
    image: postgres:15-alpine # AWS Aurora PostgreSQL compatible version
    environment:
      POSTGRES_DB: payload
      POSTGRES_USER: payload
      POSTGRES_PASSWORD: payload
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U payload']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - payload-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  localstack:
    container_name: '${LOCALSTACK_DOCKER_NAME:-localstack-multi-tenancy}'
    image: localstack/localstack-pro
    ports:
      - '4566:4566'
    environment:
      - PERSISTENCE=1
    volumes:
      - '${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack'
      - ./scripts/localstack-init.sh:/docker-entrypoint-initaws.d/init.sh

volumes:
  postgres_data:
  node_modules:
